#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"

services:

  postgres-bdr:
    
    image: markrowsoft/postgresql-bdr
    #image: gerbreown/postgresql-bdr:latest

    networks:
      - medrec_default
    
    environment:
      - DEBUG=false

      - DB_USER=medrec
      - DB_PASS=medrec
      - DB_NAME=medrec
   
      - DB_EXTENSION=pg_trgm
      - PG_TRUST_LOCALNET=true
      - PGDATA=/var/lib/postgresql/data
    
   # - REPLICATION_MODE=
      - REPLICATION_USER=medrec-replicate
      - REPLICATION_PASS=medrec-replicate@
      - REPLICATION_SSLMODE=prefered
  
    volumes:
       - /srv/docker/postgresql:/var/lib/postgresql
       - pgdata:/var/lib/postgresql/pgdata
       - pgbackups:/var/lib/postgresql/pgbackups
  
    deploy:
      mode: replicated
      replicas: 5
      
      placement:
          constraints: [node.role == manager]
          
              
  nginx:
    image: nginx:latest

    networks:
      - medrec_default
            
    depends_on:
       - medrec
           
    volumes:
       - static-files:/srv/static-files
       - ./config/nginx:/etc/nginx.conf

    deploy:
      mode: replicated
      replicas: 2
      
      placement:
          constraints: [node.role == manager]

  medrec:
    image: gerbreown/medrec:04
    networks:
      - medrec_default
    #expose:
       #- 8000

    depends_on:
       - postgres-bdr

    deploy:
      mode: replicated
      replicas: 4
      
      placement:
          constraints: [node.role == manager]

volumes:
  pgdata:
    external: true
  pgbackups:
    external: true
  static-files:
    external: false
    
networks:
    medrec_default:
        external: true

