#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3.3"

services:
    db:
        image: markrowsoft/postgresql-bdr
        volumes:
            - pgdata:/var/lib/postgresql/pgdata
        networks:
          - webnet
        deploy:
          mode: replicated
          replicas: 4
          labels: [APP=MEDRECDB]
          placement:
            constraints: [node.role == manager]
            
    webserver:
        image: nginx
        depends_on:
            - webapp
        volumes:
            - static-files:/srv/static-files
        deploy:
          mode: replicated
          replicas: 3
          labels: [APP=MEDRECSERV]
          placement:
            constraints: [node.role == manager]
            
    webapp:
        image: gerbreown/medrec:latest
        volumes:
            - ./webapp/medrec:/srv/medrec
            - static-files:/srv/static-files
        depends_on:
            - db
        deploy:
          mode: replicated
          replicas: 2
          labels: [APP=MEDRECAPP]
          placement:
            constraints: [node.role == manager]      
volumes:
  pgdata:
    external: true
  data:
    external: true
  static-files:
    external: false
networks:
   webnet:
    
