#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3.3"

services:

  db:
     #image: markrowsoft/postgresql-bdr
     #image: polinux/postgres-bdr
     image: safenetlabs/postgres-bdr

     environment:
       - POSTGRES_USER:'medrec'
       - POSTGRES_PASSWORD:'medrec'
       - POSTGRES_DB:'medrec'
     ports:
       - '5432'
     volumes:
         - pgdata:/var/lib/postgresql/pgdata
     networks:
       - webnet
     #restart: always
     container_name: pg01

  nginx:
     image: nginx:latest
     container_name: ng01
     ports:
       - "8000:8000"
     #restart: always
     depends_on:
         - web
     volumes:
        #    - static-files:/srv/static-files
         - ./src:/src
         - ./config/nginx:/etc/nginx.conf
     env_file:
         - ./config/environment/development.env
        #deploy:
          #mode: replicated
          #replicas: 3
          #labels: [APP=MEDRECSERV]
          #placement:
            #constraints: [node.role == manager]

  web:
        #image: gerbreown/medrec:latest
     build: .
     container_name: dg01
     #command: bash -c "/usr/bin/pyhon3 manage.py makemigrations && python manage.py migrate"
     #restart: always
     depends_on:
         - db
     volumes:
         - .:/code
         #- ./web/medrec:/srv/medrec
         #- static-files:/srv/static-files
         #- ./src:/src
     env_file:
         - ./config/environment/development.env
     #ports:
         #- "8000:8000"

volumes:
  pgdata:
    external: true
  data:
    external: true
  static-files:
    external: false
networks:
   webnet:

