#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3.4"
services:
  mariadb:
    image: mariadb
    #deploy:
      #mode: replicated
      #replicas: 4
      #placement:
          #constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: CasC#373
      MYSQL_DATABASE: medrec
      MYSQL_USER: medrec
      MYSQL_PASSWORD: M3dR3c#
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - medrec_default

  nginx:
    #image: gerbreown/nginx:latest
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/medrec/static
    ports:
      - 81:80

    depends_on:
      - medrec

    #deploy:
       #mode: replicated
       #replicas: 2
       #placement:
          #constraints: [node.role == manager]
    networks:
      - medrec_default

  medrec:
    #image: gerbreown/medrec:09
    build: .
    ports:
      - "8001:8001"
    networks:
      - medrec_default

    depends_on:
       - mariadb

    #deploy:
      #mode: replicated
      #replicas: 5
      #placement:
          #constraints: [node.role == manager]

volumes:
  db-data:
    external: false
  static-files:
    external: false

networks:
    medrec_default:
        external: false

