#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"

services:

  db:
     image: markrowsoft/postgresql-bdr
     #image: polinux/postgres-bdr
     #image: safenetlabs/postgres-bdr
     #expose:
       #- 5432
     environment:
       - POSTGRES_USER=medrec
       - POSTGRES_PASSWORD=medrec
       - POSTGRES_DB=medrec
     volumes:
         - pgdata:/var/lib/postgresql/pgdata
         - pgbackups:/var/lib/postgresql/pgbackups

    #restart: always
     #hostname: db.weave.local
     #container_name: pg01

  nginx:
     image: nginx:latest
     #container_name: ng01
     #ports:
       #- "8000:8000"
     #restart: always
     depends_on:
         - medrec
     volumes:
         - static-files:/srv/static-files
         - ./config/nginx:/etc/nginx.conf
     env_file:
         - ./medrec/config/environment/development.env
     deploy:
        mode: replicated
        replicas: 3
        labels: [APP=MEDRECSERV]
        placement:
            constraints: [node.role == manager]

  medrec:
     image: gerbreown/medrec:latest
     #build: .
     #container_name: dg01
     #expose:
         #- "8000"
     depends_on:
         - db
     # command: bash -c "/usr/bin/pyhon3 manage.py makemigrations && python manage.py migrate"
     #restart: always
     #env_file:
         #- ./config/environment/development.env


volumes:
  pgdata:
    external: true
  pgbackups:
    external: true
  static-files:
    external: false
#networks:
   #webnet:

