#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"
services:
  postgres-bdr:
     # image: postgres:latest
    #image: jgiannuzzi/postgres-bdr:latest
    #image: markrowsoft/postgresql-bdr
    #image: gerbreown/postgres-bdr:latest
    image: safenetlabs/postgres-bdr
    networks:
      - medrec_default
    environment:
      - DB_USER=medrec
      - DB_PASS=medrec123
      - DB_NAME=medrec
      - DB_EXTENSION=pg_trgm
      - PG_TRUST_LOCALNET=true
      - PGDATA=/var/lib/postgresql/data
   # - REPLICATION_MODE=
      - REPLICATION_USER=medrec-replicate
      - REPLICATION_PASS=medrec-replicate@
      - REPLICATION_SSLMODE=prefered
    volumes:
       - /srv/medrec/postgresql:/var/lib/postgresql
      # - var/lib/postgresql:/srv/medrec/postgresql
       - pgdata:/var/lib/postgresql/pgdata
       - pgbackups:/var/lib/postgresql/pgbackups
    ports:
       - 5432:5432
    deploy:
      mode: replicated
      replicas: 4
      placement:
          constraints: [node.role == manager]

  nginx:
    image: nginx:latest
    ports:
      - 80:8000
    
    volumes:  
      - ./site.conf:/etc/nginx/conf.d/default.conf

  medrec:
    image: gerbreown/medrec:06
    networks:
      - medrec_default
    ports:
      - 8000:8000
    depends_on:
       - postgres-bdr
    deploy:
      mode: replicated
      replicas: 4
      placement:
          constraints: [node.role == manager]

  #redis:
    #image: redis:latest
    #ports:
      #- "6379:6379"
    #volumes:
      #- redisdata:/data

volumes:
  pgdata:
    external: true
  pgbackups:
    external: true
  static-files:
    external: false
  #redisdata:
    #external: false

networks:
    medrec_default:
        external: false

