FROM python:3.6.3

MAINTAINER Gerald S. Brown <gbrown@gerbreown.com>

ENV PYTHONUNBUFFERED 1

# Install application requirements
RUN mkdir /medrec
WORKDIR /medrec

COPY requirements.txt /medrec/ 
COPY entrypoint.sh /medrec/

RUN  pip3 install --no-cache-dir -r ./requirements.txt

COPY  . /medrec/

# ENV DJANGO_ENV=prod

# Create django user, will own the Django app
RUN adduser --no-create-home --disabled-login --group --system django
RUN chown -R django:django /medrec/

EXPOSE 8000

# Execute start script
ENTRYPOINT ["./entrypoint.sh"]
