#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3.4"
services:
  postgres-bdr:
     # image: postgres:latest
    #image: jgiannuzzi/postgres-bdr:latest
    #image: markrowsoft/postgresql-bdr
    #image: gerbreown/postgres-bdr:latest
    image: safenetlabs/postgres-bdr:latest
    
    networks:
      - medrec_default
    
    environment:
      - DB_USER=medrec
      - DB_PASS=medrec123
      - DB_NAME=medrec
      - PG_TRUST_LOCALNET=true
      - REPLICATION_USER=medrec-replicate
      - REPLICATION_PASS=medrec-replicate@
      - REPLICATION_SSLMODE=prefered
    volumes:
       - pgdata:/var/lib/postgresql/data
       - pgbackups:/var/lib/postgresql/pgbackups
    #ports:
       #- 5432:5432
    deploy:
      mode: replicated
      replicas: 4
      placement:
          constraints: [node.role == manager]


  nginx:
    image: gerbreown/nginx:latest
    #image: nginx:latest
    ports:
      - 80:80
    
    #volumes:  
      #- ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./static:/usr/share/nginx/medrec/static
     
    deploy:
       mode: replicated
       replicas: 2
       placement:
          constraints: [node.role == manager] 
     

  medrec:
    image: gerbreown/medrec:07
    networks:
      - medrec_default
        
    depends_on:
       - postgres-bdr
       
    deploy:
      mode: replicated
      replicas: 5
      placement:
          constraints: [node.role == manager]
          
volumes:
  pgdata:
    external: false
  pgbackups:
    external: false
  static-files:
    external: false
  
networks:
    medrec_default:
        external: false

