#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"

services:

  postgres-master:
    #image: markrowsoft/postgresql-bdr
     #image: polinux/postgres-bdr
     image: safenetlabs/postgres-bdr
    environment:
        - POSTGRES_ROLE=medrec
        - POSTGRES_USER=medrec
        - POSTGRES_PASSWORD=medrec
        - POSTGRES_DB=medrec
        - APP_SECRET_KEY="zc_@l(+kgfrg!#*z^2zive^y@24#h#@6u^w^c*ux#x9fv0day"
        - PG_TRUST_LOCALNET=true

    ports:
        - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/pgdata
        - pgbackups:/var/lib/postgresql/pgbackups

    networks:
       - medrec_default

    deploy:
        mode: replicated
        replicas: 5
        labels: [APP=MEDRECDB]
        placement:
            constraints: [node.role == manager]
  nginx:
    image: gerbreown/nginx
      
    depends_on:
       - medrec
    volumes:
       - static-files:/srv/static-files
       - ./config/nginx:/etc/nginx.conf

    networks:
       - medrec_default

    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=MEDRECSERV]
      placement:
          constraints: [node.role == manager]

  medrec:
    image: gerbreown/medrec:latest

    depends_on:
       - postgres-master

    env_file:
       env_file

    networks:
       - medrec_default

    deploy:
      mode: replicated
      replicas: 4
      labels: [APP=MEDRECAPP]
      placement:
          constraints: [node.role == manager]

volumes:
  pgdata:
    external: true
  pgbackups:
    external: true
  static-files:
    external: false

networks:
  medrec_default:
    driver: overlay

