#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"

volumes:
    static-files:
    
    
services:
    db:
        restart: always
        image: postgres:9.6
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - ./config/environment/development.env

    webserver:
        restart: always
        build:
            context: .
            dockerfile: services/webserver/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - webapp
        volumes:
            - static-files:/srv/static-files
        env_file:
            - ./config/environment/development.env

    webapp:
        restart: always
        build:
            context: webapp
        volumes:
            - ./webapp/medrec:/srv/medrec
            - static-files:/srv/static-files
        expose:
            - "8000"
        depends_on:
            - db
        env_file:
            - ./config/environment/development.env

volumes:
  data:
    external: true

  static-files:
    external: false
