#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "2"
services:
    db:
        image: postgres:9.6
        volumes:
            - /opt/starter/psql:/var/lib/postgresql/data/pgdata
        env_file:
            - ./config/environment/development.env

    webserver:
        build:
            context: .
            dockerfile: services/webserver/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - webapp
        volumes_from:
            - webapp
        env_file:
            - ./config/environment/development.env

    webapp:
        build:
            context: webapp
        volumes:
            - ./webapp/starter:/srv/starter
            - /srv/static-files
        expose:
            - "8000"
        depends_on:
            - db
        env_file:
            - ./config/environment/development.env
